Product page on template
PyshnovT/fake-burrberry-frontend pull request #1
Opened 2017-07-31 23:00 UTC by PyshnovT

2017-08-01 11:41 UTC, evgenyrodionov commented
https://rawgit.com/PyshnovT/fake-burrberry-frontend/feat/product-page/index.html

Надо воткнуть meta viewport чтобы подстраивалися под размер экрана

![image](https://user-images.githubusercontent.com/775692/28823672-7936cfea-76c7-11e7-9b88-0f6404c5c5fb.png)

2017-08-01 11:41 UTC, evgenyrodionov commented
Бордеры слишком толстые, цена тоже

2017-08-01 11:42 UTC, imevro requested changes
фикси дизайн

2017-08-01 23:26 UTC, PyshnovT commented
усе, пиксель перфект

2017-08-01 23:29 UTC, PyshnovT reviewed
t

2017-08-02 10:18 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28869204-a5ba23a6-7784-11e7-9c3d-3af60c9079a8.png)
![image](https://user-images.githubusercontent.com/775692/28869237-b41c9258-7784-11e7-9cd3-2cdcfaf04873.png)
![image](https://user-images.githubusercontent.com/775692/28869244-bde310d2-7784-11e7-919d-dce07e72dbe8.png)
![image](https://user-images.githubusercontent.com/775692/28869253-c71202b2-7784-11e7-998f-c8785a47c4ee.png)
![image](https://user-images.githubusercontent.com/775692/28869268-cf7495a0-7784-11e7-9318-914de486d1bf.png)
![image](https://user-images.githubusercontent.com/775692/28869286-defaa1f4-7784-11e7-89c9-a4a94dec0f0e.png)

2017-08-02 10:18 UTC, imevro requested changes
↑

2017-08-02 19:18 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28890639-5dbcc1fc-77d0-11e7-81d7-26063417fed8.png)
![image](https://user-images.githubusercontent.com/775692/28890654-70247d9e-77d0-11e7-9328-e4a6e04cd861.png)
![image](https://user-images.githubusercontent.com/775692/28890660-7659ec1c-77d0-11e7-97d6-95672d6715e2.png)

2017-08-02 19:20 UTC, imevro requested changes

2017-08-02 19:20 UTC, evgenyrodionov commented on index.html
> +              <img src="img/icon-close.svg">
в цсс

2017-08-02 19:20 UTC, evgenyrodionov commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1">
группируй нормально, почему мета идёт между стилями

2017-08-02 19:20 UTC, evgenyrodionov commented on index.html
> +            <button class="product-info-colorpicker-button colorpicker-button-black"></button>
где тип кнопки? где контент внутри неё для скринридеров?

2017-08-02 19:20 UTC, evgenyrodionov commented on index.html
> +              Outer: 100% cotton<br>
это список

2017-08-02 19:20 UTC, evgenyrodionov commented on index.html
> +            <p class="product-description-content-text">A refined car coat crafted in protective cotton gabardine.<br>
это несколько параграфов

2017-08-03 12:21 UTC, evgenyrodionov commented
После 12 — след проверка

2017-08-04 09:19 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28962627-ef8681d8-790e-11e7-9ee4-6f2215ad1c87.png)
![image](https://user-images.githubusercontent.com/775692/28962640-f8fb4e56-790e-11e7-81ef-f3517fd57922.png)
![image](https://user-images.githubusercontent.com/775692/28962652-04f71dc0-790f-11e7-931b-2b4c1241463a.png)
![image](https://user-images.githubusercontent.com/775692/28962678-1a90c2f8-790f-11e7-9c68-f60c5d38e0af.png)

2017-08-04 09:23 UTC, imevro requested changes
- проблемы в описании
- Смешивание классов сетки и своих
- Списки не для списков
- Задротские селекторы

2017-08-04 09:23 UTC, evgenyrodionov commented on index.html
> +            <section class="footer-links-column col-md-3">
бессмысленно оставлять

2017-08-04 09:23 UTC, evgenyrodionov commented on index.html
> +      <main class="container container-fluid">
лол pick one

2017-08-04 09:23 UTC, evgenyrodionov commented on index.html
> +            <section class="product-recommend-card col-xs-6 col-md-3">
это не секшн

2017-08-04 09:23 UTC, evgenyrodionov commented on css/main.css
> +.ul-list {
нет

2017-08-04 09:23 UTC, evgenyrodionov commented on css/main.css
> +    display: none;
и с хуя ли

2017-08-04 09:23 UTC, evgenyrodionov commented on css/main.css
> +  .full-width-xs {
мусор убери

2017-08-04 09:23 UTC, evgenyrodionov commented on css/main.css
> +  text-indent: -9999px;
что это

2017-08-04 09:31 UTC, PyshnovT commented on css/main.css
> +  text-indent: -9999px;
Я загуглил, так убираю текст внутри кнопки, лол

2017-08-05 10:23 UTC, evgenyrodionov commented on css/main.css
> +  text-indent: -9999px;
говно

2017-08-05 10:27 UTC, imevro requested changes

2017-08-05 10:27 UTC, evgenyrodionov commented on index.html
> +            <a class="product-recommend-card col-xs-6 col-md-3" href="#">
нельзя смешивать свои классы и класы сетки

2017-08-05 10:27 UTC, evgenyrodionov commented on index.html
> +              <div class="footer-links-list">
nav

2017-08-05 14:40 UTC, PyshnovT commented on index.html
> +              <div class="footer-links-list">
Я его не слушаю, ну такое. Только трек Myself норм

2017-08-05 19:13 UTC, evgenyrodionov commented on index.html
> +              <div class="footer-links-list">
ты больше по Metro Boomin' и Desiigner? вроде твоя возрастная категория

2017-08-05 19:15 UTC, imevro requested changes

2017-08-05 19:15 UTC, evgenyrodionov commented on index.html
> +              <section class="product-info-size">
у тебя секшен стал вместо дивов? секшн для больших секций!

2017-08-06 07:49 UTC, evgenyrodionov commented
Колонки не как в макете, пикча улетела от описания

![image](https://user-images.githubusercontent.com/775692/29001494-dfa49782-7a94-11e7-9866-ba527747d6d6.png)

2017-08-06 07:50 UTC, evgenyrodionov commented
После этого делаешь мердж через сквош

2017-08-06 09:50 UTC, merged