Product page on React
PyshnovT/fake-burrberry-frontend pull request #2
Opened 2017-08-11 16:45 UTC by PyshnovT

2017-08-11 19:19 UTC, imevro requested changes
читай телеграф, поставь преттир

2017-08-11 19:19 UTC, evgenyrodionov commented on src/Footer/Navigation.js
> +          <Link class="footer-link" href="#">Payment</Link>
зачем тебе классы (опять же должно быть класснейм) если у тебя ск

2017-08-11 19:19 UTC, evgenyrodionov commented on src/Footer/index.js
> +        <div className="container container-fluid">
что с отступами

2017-08-11 19:20 UTC, PyshnovT commented on src/Footer/Navigation.js
> +          <Link class="footer-link" href="#">Payment</Link>
случайно оставил

2017-08-12 10:02 UTC, imevro requested changes

2017-08-12 10:02 UTC, evgenyrodionov commented on src/Product/Delivery/ShippingAccordion.js
> +        active: !prevState.active
поставь преттир, заебал

2017-08-12 10:02 UTC, evgenyrodionov commented on src/Product/Info/ColorButton.js
> +      <Text>Change color to black</Text>
почему to black

2017-08-12 10:02 UTC, evgenyrodionov commented on src/Product/Info/Images.js
> +        <Image className="product-info-image" src="img/guy5@3x.jpg" alt="Long Cotton Gabardine Car Coat" />
откуда класснейм

2017-08-12 10:02 UTC, evgenyrodionov commented on src/Product/Info/Panel.js
> +        <SizeButtons>
не понял

2017-08-12 10:02 UTC, evgenyrodionov commented on src/Product/Info/Panel.js
> +          <Button black>SELECT A SIZE</Button>
телеграф про дизайн и систему

2017-08-12 10:02 UTC, evgenyrodionov commented on src/Product/Recommendation/index.js
> +/* вынести */
вынеси

2017-08-12 18:47 UTC, imevro requested changes

2017-08-12 18:47 UTC, evgenyrodionov commented on src/Product/Delivery/index.js
> +            <P>
P? wtf???

2017-08-12 18:47 UTC, evgenyrodionov commented on src/Product/Info/Image.js
> +    <Image src={props.src} alt={props.alt} />
зачем эта прокладка

2017-08-12 18:47 UTC, evgenyrodionov commented on src/Product/Info/Panel/ButtonHelp.js
> +const ButtonHelp = styled.button`
плохое название

2017-08-12 18:47 UTC, evgenyrodionov commented on src/Product/Info/Panel/ColorButton.js
> +class ColorButton extends Component {
зачем тут класс

2017-08-12 18:47 UTC, evgenyrodionov commented on src/Product/Info/Panel/ColorPicker.js
> +    const colorValues = ["#232122", "#cfa880"];
в один объект засунь с ключами label, value

2017-08-12 18:47 UTC, evgenyrodionov commented on src/Product/Info/Panel/ColorPicker.js
> +    const colorValues = ["#232122", "#cfa880"];
и вынеси за пределы рендера

2017-08-12 18:47 UTC, evgenyrodionov commented on src/Product/Info/Panel/SizePicker.js
> +          {sizeButtons}
мап тут хуярь

2017-08-12 18:47 UTC, evgenyrodionov commented on src/Product/index.js
> +  const Desktop = ({ children }) =>
зачем это здесь?

2017-08-12 18:47 UTC, evgenyrodionov commented on src/common/Responsive.js
> +const Mobile = ({ children }) =>
телеграф

2017-08-13 10:18 UTC, imevro requested changes

2017-08-13 10:18 UTC, evgenyrodionov commented on src/index.js
> +import { IntlProvider, addLocaleData } from "react-intl";
телеграф

2017-08-13 10:22 UTC, evgenyrodionov commented
Доделывай

2017-08-13 10:23 UTC, evgenyrodionov commented
Как доделаешь — напиши в личку

2017-08-13 12:55 UTC, imevro approved these changes

2017-08-13 12:55 UTC, merged